"""first

Revision ID: 8223465e4710
Revises: 
Create Date: 2022-11-19 22:40:39.505434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8223465e4710'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CATEGORY',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('CITY',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('USER',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('UserName', sa.String(length=20), nullable=False),
    sa.Column('Password', sa.String(length=80), nullable=False),
    sa.Column('Name', sa.String(length=255), nullable=True),
    sa.Column('PhoneNumber', sa.String(), nullable=True),
    sa.Column('Address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=120), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entry_description'), 'entry', ['description'], unique=False)
    op.create_index(op.f('ix_entry_title'), 'entry', ['title'], unique=False)
    op.create_table('PRODUCT',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=255), nullable=True),
    sa.Column('Description', sa.String(), nullable=True),
    sa.Column('ImageUrl', sa.String(), nullable=True),
    sa.Column('Status', sa.Integer(), nullable=True),
    sa.Column('Surcharge', sa.Integer(), nullable=True),
    sa.Column('Receiver', sa.Integer(), nullable=True),
    sa.Column('UserId', sa.Integer(), nullable=True),
    sa.Column('CategoryId', sa.Integer(), nullable=True),
    sa.Column('CityId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['CategoryId'], ['CATEGORY.Id'], ),
    sa.ForeignKeyConstraint(['CityId'], ['CITY.Id'], ),
    sa.ForeignKeyConstraint(['UserId'], ['USER.id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('PRODUCT')
    op.drop_index(op.f('ix_entry_title'), table_name='entry')
    op.drop_index(op.f('ix_entry_description'), table_name='entry')
    op.drop_table('entry')
    op.drop_table('USER')
    op.drop_table('CITY')
    op.drop_table('CATEGORY')
    # ### end Alembic commands ###
